import { useEffect, useMemo, useState } from 'react'
import { Check, Eye, FileText, Flag, Loader2, RefreshCw, Search, X, XCircle } from 'lucide-react'
import { SellerLayout } from '../../components/layout/SellerLayout'
import { api } from '../../services/api'
import { getSellerRefunds, updateSellerRefund } from '../../services/refunds.service'

type Refund = { id: string; orderId: string; amount: number; reason: string; status: string; sellerNote?: string | null; requestedAt: string; processedAt?: string | null; customer?: { name?: string; email?: string }; order?: { id: string; items?: Array<{ name: string }> }; payment?: { status?: string } | null }
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' })
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
function tone(status: string) { const normalized = status.toUpperCase(); if (['APPROVED', 'COMPLETED'].includes(normalized)) return 'bg-emerald-50 text-emerald-700 ring-emerald-200'; if (['REQUESTED', 'PENDING', 'PROCESSING'].includes(normalized)) return 'bg-amber-50 text-amber-700 ring-amber-200'; return 'bg-red-50 text-red-700 ring-red-200' }
function normalizeStatus(status: string) { return status === 'REQUESTED' ? 'PENDING' : status }

export function SellerRefundRequestsPage() {
  const [refunds, setRefunds] = useState<Refund[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [selected, setSelected] = useState<Refund | null>(null)
  const [workingId, setWorkingId] = useState<string | null>(null)
  const [note, setNote] = useState('')

  const load = async () => { setLoading(true); setError(''); try { setRefunds(await getSellerRefunds<Refund[]>()) } catch (loadError: any) { setError(loadError?.response?.data?.message || loadError?.message || 'Unable to load refund requests.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])

  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return refunds.filter((refund) => (!query || refund.id.toLowerCase().includes(query) || refund.orderId.toLowerCase().includes(query) || refund.customer?.name?.toLowerCase().includes(query) || refund.reason.toLowerCase().includes(query)) && (!status || normalizeStatus(refund.status) === status)) }, [refunds, search, status])
  const update = async (refund: Refund, payload: { status?: string; sellerNote?: string }) => { setWorkingId(refund.id); setError(''); setNotice(''); try { await updateSellerRefund(refund.id, payload); setNotice(payload.sellerNote ? 'Refund note saved.' : `Refund marked ${payload.status?.toLowerCase()}.`); setSelected(null); setNote(''); await load() } catch (updateError: any) { setError(updateError?.response?.data?.message || updateError?.message || 'Unable to update refund request.') } finally { setWorkingId(null) } }
  const openDetail = (refund: Refund) => { setSelected(refund); setNote(refund.sellerNote || '') }

  return <SellerLayout title="Refund requests" subtitle="Review and resolve refund requests raised against your store." actions={<button type="button" onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700"><RefreshCw size={15} className={loading ? 'animate-spin' : ''} /> Refresh</button>}>
    <div className="space-y-5">
      {error ? <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div> : null}{notice ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</div> : null}
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-3"><label className="relative min-w-[260px] flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search refund, order, customer..." className="w-full rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-[#2d80d8]" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">All statuses</option><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="COMPLETED">Completed</option></select><button type="button" onClick={() => { setSearch(''); setStatus('') }} className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-medium text-slate-600">Clear filters</button></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="space-y-3 p-4">{Array.from({ length: 5 }).map((_, index) => <div key={index} className="h-16 animate-pulse rounded-lg bg-slate-100" />)}</div> : !filtered.length ? <div className="p-14 text-center"><FileText className="mx-auto text-slate-300" size={36} /><p className="mt-3 text-sm font-semibold text-slate-600">{refunds.length ? 'No refund requests match your filters.' : 'No refund requests yet.'}</p></div> : <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[0.1em] text-slate-500"><tr>{['Refund ID', 'Order', 'Customer', 'Product', 'Amount', 'Reason', 'Status', 'Requested date', 'Actions'].map((heading) => <th key={heading} className="px-4 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody>{filtered.map((refund) => <tr key={refund.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-4 py-4 font-mono text-xs font-semibold text-slate-700">{refund.id.slice(0, 12)}</td><td className="px-4 py-4 font-mono text-xs text-slate-600">{refund.orderId.slice(0, 12)}</td><td className="px-4 py-4"><div className="font-medium text-slate-800">{refund.customer?.name || 'Customer'}</div><div className="text-xs text-slate-500">{refund.customer?.email || ''}</div></td><td className="max-w-[180px] px-4 py-4 text-slate-600">{refund.order?.items?.map((item) => item.name).join(', ') || 'Order products'}</td><td className="px-4 py-4 font-semibold text-slate-800">{money.format(refund.amount)}</td><td className="max-w-[220px] px-4 py-4 text-slate-600">{refund.reason}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ring-1 ${tone(refund.status)}`}>{normalizeStatus(refund.status)}</span></td><td className="whitespace-nowrap px-4 py-4 text-xs text-slate-500">{date(refund.requestedAt)}</td><td className="px-4 py-4"><div className="flex items-center gap-1.5"><button type="button" title="View refund" onClick={() => openDetail(refund)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Eye size={16} /></button>{['REQUESTED', 'PENDING'].includes(refund.status) ? <><button type="button" title="Approve refund" disabled={workingId === refund.id} onClick={() => void update(refund, { status: 'APPROVED' })} className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-50 disabled:opacity-40"><Check size={16} /></button><button type="button" title="Reject refund" disabled={workingId === refund.id} onClick={() => void update(refund, { status: 'REJECTED' })} className="rounded-lg p-2 text-red-600 hover:bg-red-50 disabled:opacity-40"><XCircle size={16} /></button></> : null}<button type="button" title="Add note" onClick={() => openDetail(refund)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Flag size={16} /></button></div></td></tr>)}</tbody></table></div>}</section>
    </div>
    {selected ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Refund request</div><h2 className="mt-1 text-xl font-black text-slate-900">{selected.id}</h2></div><button type="button" aria-label="Close refund details" onClick={() => setSelected(null)} className="rounded-full p-2 text-slate-500 hover:bg-slate-100"><X size={18} /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><span className="text-xs text-slate-500">Order</span><p className="font-mono text-sm">{selected.orderId}</p></div><div><span className="text-xs text-slate-500">Customer</span><p className="font-medium">{selected.customer?.name || 'Customer'}</p></div><div><span className="text-xs text-slate-500">Amount</span><p className="font-bold">{money.format(selected.amount)}</p></div><div><span className="text-xs text-slate-500">Status</span><p><span className={`inline-flex rounded-full px-2 py-1 text-xs font-semibold ring-1 ${tone(selected.status)}`}>{normalizeStatus(selected.status)}</span></p></div></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Reason</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{selected.reason}</p></div><label className="mt-5 block text-sm font-medium text-slate-700">Seller note<textarea rows={4} maxLength={2000} value={note} onChange={(event) => setNote(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 outline-none focus:border-[#2d80d8]" placeholder="Add an internal note for this refund request..." /></label><div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" disabled={!note.trim() || workingId === selected.id} onClick={() => void update(selected, { sellerNote: note.trim() })} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Save note</button>{['REQUESTED', 'PENDING'].includes(selected.status) ? <><button type="button" disabled={workingId === selected.id} onClick={() => void update(selected, { status: 'REJECTED' })} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-700">Reject</button><button type="button" disabled={workingId === selected.id} onClick={() => void update(selected, { status: 'APPROVED' })} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Approve</button></> : null}</div></div></div> : null}
  </SellerLayout>
}
