import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import axios from 'axios'

type Product = { id: string; name: string; sku: string; category?: string; brand?: string; basePrice: number; stock: number; status: string }
type Plan = { id: string; name: string; price: number; productLimit: number; duration: number; status: string }

const api = axios.create({ baseURL: import.meta.env.VITE_API_BASE_URL || '/api' })
api.interceptors.request.use((config) => { const token = localStorage.getItem('accessToken') || localStorage.getItem('access_token'); if (token) config.headers.Authorization = `Bearer ${token}`; return config })

export function ProductWarehouse() {
  const [products, setProducts] = useState<Product[]>([])
  const [plans, setPlans] = useState<Plan[]>([])
  const [form, setForm] = useState({ name: '', sku: '', category: '', brand: '', basePrice: '', stock: '' })
  const [error, setError] = useState('')

  const load = () => Promise.all([api.get('/admin/product-warehouse?limit=100'), api.get('/admin/subscription-plans')]).then(([productResponse, planResponse]) => { setProducts(productResponse.data.items || []); setPlans(planResponse.data || []) }).catch(() => setError('Unable to load warehouse management data.'))
  useEffect(() => { void load() }, [])
  const createProduct = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await api.post('/admin/product-warehouse', { ...form, basePrice: Number(form.basePrice), stock: Number(form.stock), status: 'PUBLISHED' }); setForm({ name: '', sku: '', category: '', brand: '', basePrice: '', stock: '' }); await load() } catch { setError('Unable to create warehouse product.') } }
  const toggle = async (product: Product) => { await api.patch(`/admin/product-warehouse/${product.id}`, { status: product.status === 'PUBLISHED' ? 'INACTIVE' : 'PUBLISHED' }); await load() }
  const remove = async (id: string) => { if (window.confirm('Delete this warehouse product?')) { await api.delete(`/admin/product-warehouse/${id}`); await load() } }

  return <div className="min-h-screen bg-[#edf2f8] p-6 text-slate-800"><div className="mx-auto max-w-7xl space-y-6"><div><h1 className="text-2xl font-semibold">Product Warehouse</h1><p className="mt-1 text-sm text-slate-500">Manage the approved product catalog sellers can add to their shops.</p></div>{error ? <div className="rounded border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</div> : null}<div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={createProduct} className="space-y-3 rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Create warehouse product</h2>{(['name', 'sku', 'category', 'brand', 'basePrice', 'stock'] as const).map((field) => <input key={field} required={field === 'name' || field === 'sku' || field === 'basePrice'} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} placeholder={field === 'basePrice' ? 'Base price' : field[0].toUpperCase() + field.slice(1)} type={field === 'basePrice' || field === 'stock' ? 'number' : 'text'} className="w-full rounded border border-slate-200 px-3 py-2 text-sm" />)}<button className="w-full rounded bg-[#2d80d8] px-4 py-2 text-sm font-medium text-white">Create Product</button></form><section className="rounded-lg border border-slate-200 bg-white p-5"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase text-slate-500"><tr><th className="p-3">Product</th><th className="p-3">SKU</th><th className="p-3">Price</th><th className="p-3">Stock</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{products.map((product) => <tr key={product.id} className="border-b border-slate-100"><td className="p-3 font-medium">{product.name}</td><td className="p-3 text-slate-500">{product.sku}</td><td className="p-3">${product.basePrice.toFixed(2)}</td><td className="p-3">{product.stock}</td><td className="p-3">{product.status}</td><td className="flex gap-2 p-3"><button onClick={() => void toggle(product)} className="text-blue-600">{product.status === 'PUBLISHED' ? 'Deactivate' : 'Activate'}</button><button onClick={() => void remove(product.id)} className="text-red-600">Delete</button></td></tr>)}</tbody></table>{!products.length ? <div className="py-12 text-center text-sm text-slate-500">No warehouse products found.</div> : null}</div></section></div><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="mb-4 font-semibold">Subscription plans</h2><div className="grid gap-3 md:grid-cols-4">{plans.map((plan) => <div key={plan.id} className="rounded border border-slate-200 p-4"><div className="font-medium">{plan.name}</div><div className="mt-2 text-xl font-semibold">{plan.productLimit < 0 ? 'Unlimited' : plan.productLimit}</div><div className="text-xs text-slate-500">products, ${plan.price}/month</div></div>)}</div></section></div></div>
}
